<?php

namespace Database\Seeders;

use App\Enums\LabTestCategory;
use App\Enums\SampleType;
use App\Models\LabPackage;
use App\Models\LabTest;
use Illuminate\Database\Seeder;

class LabCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $tests = [];

        foreach ($this->tests() as $index => $test) {
            $tests[$test['code']] = LabTest::updateOrCreate(
                ['slug' => $test['code']],
                [
                    ...collect($test)->except('code')->all(),
                    'display_order' => $index + 1,
                    'is_active' => true,
                ],
            );
        }

        foreach ($this->packages() as $index => $package) {
            $codes = $package['tests'];
            unset($package['tests']);

            $slug = $package['slug'];
            unset($package['slug']);

            $model = LabPackage::updateOrCreate(
                ['slug' => $slug],
                [...$package, 'display_order' => $index + 1, 'is_active' => true],
            );

            $model->tests()->sync(
                collect($codes)->map(fn (string $code) => $tests[$code]?->id)->filter()->all()
            );
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function tests(): array
    {
        return [
            [
                'code' => 'cbc',
                'name_ar' => 'صورة دم كاملة (CBC)',
                'name_en' => 'Complete Blood Count (CBC)',
                'category' => LabTestCategory::Blood,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 180,
                'fasting_hours' => null,
                'turnaround_hours' => 6,
                'description_ar' => 'تحليل أساسي يقيس كريات الدم الحمراء والبيضاء والصفائح والهيموجلوبين.',
                'description_en' => 'Core blood test measuring red and white cells, platelets and haemoglobin.',
                'measures_ar' => 'الهيموجلوبين، الهيماتوكريت، عدد كريات الدم، الصفائح، مؤشرات الأنيميا.',
                'measures_en' => 'Haemoglobin, haematocrit, cell counts, platelets and anaemia indices.',
                'preparation_ar' => 'لا يحتاج صيامًا. أخبر المعمل بأي أدوية سيولة دم.',
                'preparation_en' => 'No fasting. Tell the lab if you take blood thinners.',
                'contains_ar' => 'عينة دم وريدي واحدة.',
                'contains_en' => 'One venous blood sample.',
            ],
            [
                'code' => 'lipid',
                'name_ar' => 'صورة دهون كاملة',
                'name_en' => 'Lipid Profile',
                'category' => LabTestCategory::Lipids,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 280,
                'fasting_hours' => 12,
                'turnaround_hours' => 12,
                'description_ar' => 'يقيم الكوليسترول والدهون الثلاثية ومخاطر القلب.',
                'description_en' => 'Assesses cholesterol, triglycerides and cardiac risk.',
                'measures_ar' => 'الكوليسترول الكلي، LDL، HDL، الدهون الثلاثية.',
                'measures_en' => 'Total cholesterol, LDL, HDL and triglycerides.',
                'preparation_ar' => 'صيام 10–12 ساعة مع شرب الماء. تجنب الدهون الشديدة قبلها بيوم.',
                'preparation_en' => 'Fast 10–12 hours, water allowed. Avoid a very fatty meal the day before.',
                'contains_ar' => 'عينة دم بعد الصيام.',
                'contains_en' => 'Fasting blood sample.',
            ],
            [
                'code' => 'liver',
                'name_ar' => 'وظائف كبد شاملة',
                'name_en' => 'Liver Function Tests',
                'category' => LabTestCategory::Liver,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 320,
                'fasting_hours' => 8,
                'turnaround_hours' => 12,
                'description_ar' => 'يفحص إنزيمات الكبد والبيليروبين والبروتينات.',
                'description_en' => 'Checks liver enzymes, bilirubin and proteins.',
                'measures_ar' => 'ALT، AST، GGT، ALP، البيليروبين، الألبومين، البروتين الكلي.',
                'measures_en' => 'ALT, AST, GGT, ALP, bilirubin, albumin and total protein.',
                'preparation_ar' => 'يفضّل صيام 8 ساعات. أخبر المعمل بأي أدوية كبد.',
                'preparation_en' => 'Prefer 8 hours fasting. Mention liver medication.',
                'contains_ar' => 'عينة دم وريدي.',
                'contains_en' => 'Venous blood sample.',
            ],
            [
                'code' => 'kidney',
                'name_ar' => 'وظائف كلى',
                'name_en' => 'Kidney Function Tests',
                'category' => LabTestCategory::Kidney,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 240,
                'fasting_hours' => null,
                'turnaround_hours' => 8,
                'description_ar' => 'يقيم عمل الكلى عبر الكرياتينين واليوريا وحمض اليوريك.',
                'description_en' => 'Assesses kidney function via creatinine, urea and uric acid.',
                'measures_ar' => 'الكرياتينين، اليوريا، حمض اليوريك، معدل الترشيح التقديري.',
                'measures_en' => 'Creatinine, urea, uric acid and estimated GFR.',
                'preparation_ar' => 'لا يحتاج صيامًا عادة. اشرب ماءً كالمعتاد.',
                'preparation_en' => 'Usually no fasting. Drink water as normal.',
                'contains_ar' => 'عينة دم وريدي.',
                'contains_en' => 'Venous blood sample.',
            ],
            [
                'code' => 'hba1c',
                'name_ar' => 'سكر تراكمي (HbA1c)',
                'name_en' => 'HbA1c',
                'category' => LabTestCategory::Diabetes,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 260,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يعكس متوسط السكر خلال الشهرين أو الثلاثة الماضية.',
                'description_en' => 'Reflects average blood sugar over the last 2–3 months.',
                'measures_ar' => 'نسبة الهيموجلوبين السكري.',
                'measures_en' => 'Glycated haemoglobin percentage.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting required.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'glucose',
                'name_ar' => 'سكر صائم',
                'name_en' => 'Fasting Blood Glucose',
                'category' => LabTestCategory::Diabetes,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 90,
                'fasting_hours' => 8,
                'turnaround_hours' => 4,
                'description_ar' => 'قياس الجلوكوز بعد صيام لتقييم السكري.',
                'description_en' => 'Glucose after fasting to screen for diabetes.',
                'measures_ar' => 'مستوى الجلوكوز في الدم.',
                'measures_en' => 'Blood glucose level.',
                'preparation_ar' => 'صيام 8 ساعات. الماء مسموح.',
                'preparation_en' => 'Fast 8 hours. Water is allowed.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'tsh',
                'name_ar' => 'هرمون TSH',
                'name_en' => 'TSH',
                'category' => LabTestCategory::Thyroid,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 220,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يفحص نشاط الغدة الدرقية.',
                'description_en' => 'Screens thyroid gland activity.',
                'measures_ar' => 'الهرمون المنشط للدرقية.',
                'measures_en' => 'Thyroid-stimulating hormone.',
                'preparation_ar' => 'لا يحتاج صيامًا. أخبر المعمل بأدوية الدرقية.',
                'preparation_en' => 'No fasting. Mention thyroid medication.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'ft4',
                'name_ar' => 'هرمون T4 الحر',
                'name_en' => 'Free T4',
                'category' => LabTestCategory::Thyroid,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 230,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يكمل تقييم الدرقية مع TSH.',
                'description_en' => 'Complements TSH for thyroid assessment.',
                'measures_ar' => 'الثيروكسين الحر.',
                'measures_en' => 'Free thyroxine.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'vitd',
                'name_ar' => 'فيتامين د',
                'name_en' => 'Vitamin D',
                'category' => LabTestCategory::Vitamins,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 420,
                'fasting_hours' => null,
                'turnaround_hours' => 48,
                'description_ar' => 'يكشف نقص فيتامين د المرتبط بالعظام والمناعة.',
                'description_en' => 'Detects vitamin D deficiency linked to bone and immunity.',
                'measures_ar' => '25-هيدروكسي فيتامين د.',
                'measures_en' => '25-hydroxy vitamin D.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'vitb12',
                'name_ar' => 'فيتامين ب12',
                'name_en' => 'Vitamin B12',
                'category' => LabTestCategory::Vitamins,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 380,
                'fasting_hours' => 8,
                'turnaround_hours' => 48,
                'description_ar' => 'مهم للأعصاب والأنيميا.',
                'description_en' => 'Important for nerves and anaemia workup.',
                'measures_ar' => 'مستوى كوبالامين في الدم.',
                'measures_en' => 'Serum cobalamin.',
                'preparation_ar' => 'يفضّل صيام 8 ساعات.',
                'preparation_en' => 'Prefer 8 hours fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'ferritin',
                'name_ar' => 'فيريتين',
                'name_en' => 'Ferritin',
                'category' => LabTestCategory::Iron,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 300,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'مخزون الحديد في الجسم.',
                'description_en' => 'Body iron stores.',
                'measures_ar' => 'مستوى الفيريتين.',
                'measures_en' => 'Serum ferritin.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'iron',
                'name_ar' => 'حديد السيرم',
                'name_en' => 'Serum Iron',
                'category' => LabTestCategory::Iron,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 160,
                'fasting_hours' => 8,
                'turnaround_hours' => 12,
                'description_ar' => 'الحديد المتاح في الدم.',
                'description_en' => 'Circulating iron.',
                'measures_ar' => 'تركيز الحديد.',
                'measures_en' => 'Iron concentration.',
                'preparation_ar' => 'صيام 8 ساعات. لا تتناول مكمل حديد صباح التحليل.',
                'preparation_en' => 'Fast 8 hours. Skip morning iron supplements.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'tibc',
                'name_ar' => 'سعة ارتباط الحديد (TIBC)',
                'name_en' => 'TIBC',
                'category' => LabTestCategory::Iron,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 170,
                'fasting_hours' => 8,
                'turnaround_hours' => 12,
                'description_ar' => 'يكمل صورة الحديد مع الفيريتين.',
                'description_en' => 'Completes the iron panel with ferritin.',
                'measures_ar' => 'سعة ارتباط الحديد الإجمالية.',
                'measures_en' => 'Total iron-binding capacity.',
                'preparation_ar' => 'صيام 8 ساعات.',
                'preparation_en' => 'Fast 8 hours.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'urine',
                'name_ar' => 'تحليل بول كامل',
                'name_en' => 'Complete Urine Analysis',
                'category' => LabTestCategory::Urine,
                'sample_type' => SampleType::Urine,
                'suggested_price' => 80,
                'fasting_hours' => null,
                'turnaround_hours' => 4,
                'description_ar' => 'يفحص البول للعدوى والسكر والبروتين.',
                'description_en' => 'Screens urine for infection, glucose and protein.',
                'measures_ar' => 'اللون، الكثافة، الصديد، الدم، السكر، البروتين.',
                'measures_en' => 'Colour, density, pus, blood, glucose and protein.',
                'preparation_ar' => 'عينة منتصف التبول صباحية إن أمكن. نظّف المنطقة قبل الجمع.',
                'preparation_en' => 'Midstream morning sample if possible. Clean before collection.',
                'contains_ar' => 'عينة بول في عبوة معقمة.',
                'contains_en' => 'Urine in a sterile container.',
            ],
            [
                'code' => 'esr',
                'name_ar' => 'سرعة ترسيب (ESR)',
                'name_en' => 'ESR',
                'category' => LabTestCategory::Blood,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 90,
                'fasting_hours' => null,
                'turnaround_hours' => 6,
                'description_ar' => 'مؤشر التهابي عام.',
                'description_en' => 'General inflammation marker.',
                'measures_ar' => 'معدل ترسيب كريات الدم الحمراء.',
                'measures_en' => 'Erythrocyte sedimentation rate.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'crp',
                'name_ar' => 'بروتين سي التفاعلي (CRP)',
                'name_en' => 'CRP',
                'category' => LabTestCategory::Infection,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 200,
                'fasting_hours' => null,
                'turnaround_hours' => 8,
                'description_ar' => 'يكشف الالتهاب الحاد.',
                'description_en' => 'Detects acute inflammation.',
                'measures_ar' => 'تركيز CRP.',
                'measures_en' => 'CRP concentration.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'prolactin',
                'name_ar' => 'هرمون البرولاكتين',
                'name_en' => 'Prolactin',
                'category' => LabTestCategory::Hormones,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 280,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يُطلب في اضطرابات الدورة والخصوبة.',
                'description_en' => 'Ordered for cycle and fertility workups.',
                'measures_ar' => 'مستوى البرولاكتين.',
                'measures_en' => 'Prolactin level.',
                'preparation_ar' => 'يُفضّل السحب صباحًا بعد راحة 20 دقيقة. تجنب الجماع والرياضة العنيفة قبلها.',
                'preparation_en' => 'Morning draw after 20 minutes rest. Avoid intercourse and intense exercise beforehand.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'testosterone',
                'name_ar' => 'هرمون التستوستيرون',
                'name_en' => 'Testosterone',
                'category' => LabTestCategory::Hormones,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 300,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'هرمون الذكورة وتقييم الخصوبة.',
                'description_en' => 'Male hormone and fertility assessment.',
                'measures_ar' => 'التستوستيرون الكلي.',
                'measures_en' => 'Total testosterone.',
                'preparation_ar' => 'يُفضّل السحب صباحًا.',
                'preparation_en' => 'Prefer a morning sample.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'hbsag',
                'name_ar' => 'تحليل التهاب الكبد ب (HBsAg)',
                'name_en' => 'HBsAg',
                'category' => LabTestCategory::Infection,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 190,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يكشف مستضد فيروس التهاب الكبد ب.',
                'description_en' => 'Detects hepatitis B surface antigen.',
                'measures_ar' => 'إيجابية أو سلبية HBsAg.',
                'measures_en' => 'HBsAg reactive or non-reactive.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'hcv',
                'name_ar' => 'تحليل التهاب الكبد سي (HCV Ab)',
                'name_en' => 'HCV Antibody',
                'category' => LabTestCategory::Infection,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 210,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'مسح أجسام مضادة لفيروس سي.',
                'description_en' => 'Screens for hepatitis C antibodies.',
                'measures_ar' => 'أجسام مضادة لـ HCV.',
                'measures_en' => 'HCV antibodies.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'troponin',
                'name_ar' => 'تروبونين القلب',
                'name_en' => 'Cardiac Troponin',
                'category' => LabTestCategory::Heart,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 450,
                'fasting_hours' => null,
                'turnaround_hours' => 4,
                'description_ar' => 'يساعد في تقييم إصابة عضلة القلب عند ألم الصدر.',
                'description_en' => 'Helps assess heart-muscle injury with chest pain.',
                'measures_ar' => 'تروبونين I أو T عالي الحساسية.',
                'measures_en' => 'High-sensitivity troponin I or T.',
                'preparation_ar' => 'لا يحتاج صيامًا. أخبر المعمل بأي أعراض صدر حادة.',
                'preparation_en' => 'No fasting. Tell the lab about acute chest symptoms.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'ckmb',
                'name_ar' => 'إنزيم CK-MB',
                'name_en' => 'CK-MB',
                'category' => LabTestCategory::Heart,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 280,
                'fasting_hours' => null,
                'turnaround_hours' => 8,
                'description_ar' => 'إنزيم عضلة القلب يُطلب مع التروبونين أحيانًا.',
                'description_en' => 'A cardiac enzyme sometimes ordered with troponin.',
                'measures_ar' => 'تركيز CK-MB.',
                'measures_en' => 'CK-MB concentration.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'ige',
                'name_ar' => 'الغلوبولين IgE الكلي',
                'name_en' => 'Total IgE',
                'category' => LabTestCategory::Allergy,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 340,
                'fasting_hours' => null,
                'turnaround_hours' => 48,
                'description_ar' => 'مؤشر عام للحساسية.',
                'description_en' => 'A general allergy marker.',
                'measures_ar' => 'مستوى IgE في الدم.',
                'measures_en' => 'Serum IgE level.',
                'preparation_ar' => 'لا يحتاج صيامًا. أخبر المعمل بمضادات الهيستامين.',
                'preparation_en' => 'No fasting. Mention antihistamines.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'psa',
                'name_ar' => 'تحليل PSA',
                'name_en' => 'PSA',
                'category' => LabTestCategory::TumorMarkers,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 360,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'مستضد البروستاتا للرجال فوق الأربعين عادة.',
                'description_en' => 'Prostate-specific antigen, usually for men over 40.',
                'measures_ar' => 'PSA الكلي.',
                'measures_en' => 'Total PSA.',
                'preparation_ar' => 'تجنّب الفحص الشرجي والجماع قبل التحليل بـ 48 ساعة إن أمكن.',
                'preparation_en' => 'Avoid rectal exam and intercourse for 48 hours if possible.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'cea',
                'name_ar' => 'دلالة CEA',
                'name_en' => 'CEA',
                'category' => LabTestCategory::TumorMarkers,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 390,
                'fasting_hours' => null,
                'turnaround_hours' => 48,
                'description_ar' => 'دلالة ورم تُطلب للمتابعة حسب رأي الطبيب.',
                'description_en' => 'A tumour marker used for follow-up when a doctor requests it.',
                'measures_ar' => 'المستضد السرطاني الجنيني.',
                'measures_en' => 'Carcinoembryonic antigen.',
                'preparation_ar' => 'لا يحتاج صيامًا. التدخين قد يرفع النتيجة.',
                'preparation_en' => 'No fasting. Smoking may raise the result.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'stool',
                'name_ar' => 'تحليل براز كامل',
                'name_en' => 'Complete Stool Analysis',
                'category' => LabTestCategory::Infection,
                'sample_type' => SampleType::Stool,
                'suggested_price' => 120,
                'fasting_hours' => null,
                'turnaround_hours' => 12,
                'description_ar' => 'يفحص الطفيليات والدم الخفي والعدوى المعوية.',
                'description_en' => 'Screens for parasites, occult blood and intestinal infection.',
                'measures_ar' => 'الطفيليات، كريات الدم، الدم الخفي.',
                'measures_en' => 'Parasites, blood cells and occult blood.',
                'preparation_ar' => 'عيّنة صباحية في عبوة المعمل. تجنّب المضادات إن طلب الطبيب.',
                'preparation_en' => 'Morning sample in the lab container. Avoid antibiotics if your doctor asked.',
                'contains_ar' => 'عينة براز.',
                'contains_en' => 'Stool sample.',
            ],
            [
                'code' => 'hcg',
                'name_ar' => 'هرمون الحمل (Beta HCG)',
                'name_en' => 'Beta HCG',
                'category' => LabTestCategory::Hormones,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 220,
                'fasting_hours' => null,
                'turnaround_hours' => 8,
                'description_ar' => 'يؤكد الحمل ويُستخدم في المتابعة المبكرة.',
                'description_en' => 'Confirms pregnancy and is used in early follow-up.',
                'measures_ar' => 'مستوى Beta HCG.',
                'measures_en' => 'Beta HCG level.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'calcium',
                'name_ar' => 'كالسيوم الدم',
                'name_en' => 'Serum Calcium',
                'category' => LabTestCategory::Vitamins,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 110,
                'fasting_hours' => null,
                'turnaround_hours' => 6,
                'description_ar' => 'يُطلب مع فيتامين د واضطرابات العظام.',
                'description_en' => 'Ordered with vitamin D and bone workups.',
                'measures_ar' => 'الكالسيوم الكلي.',
                'measures_en' => 'Total calcium.',
                'preparation_ar' => 'لا يحتاج صيامًا عادة.',
                'preparation_en' => 'Usually no fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'fsh',
                'name_ar' => 'هرمون FSH',
                'name_en' => 'FSH',
                'category' => LabTestCategory::Hormones,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 260,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يُطلب في تقييم الخصوبة والدورة.',
                'description_en' => 'Used in fertility and cycle assessment.',
                'measures_ar' => 'الهرمون المنبه للجريب.',
                'measures_en' => 'Follicle-stimulating hormone.',
                'preparation_ar' => 'التوقيت حسب يوم الدورة إن طلب الطبيب.',
                'preparation_en' => 'Timing may follow the cycle day if your doctor asked.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'lh',
                'name_ar' => 'هرمون LH',
                'name_en' => 'LH',
                'category' => LabTestCategory::Hormones,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 260,
                'fasting_hours' => null,
                'turnaround_hours' => 24,
                'description_ar' => 'يُطلب مع FSH في الخصوبة.',
                'description_en' => 'Ordered with FSH in fertility workups.',
                'measures_ar' => 'الهرمون المنبه للجسم الأصفر.',
                'measures_en' => 'Luteinising hormone.',
                'preparation_ar' => 'التوقيت حسب يوم الدورة إن طلب الطبيب.',
                'preparation_en' => 'Timing may follow the cycle day if your doctor asked.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
            [
                'code' => 'ana',
                'name_ar' => 'أجسام مضادة للنواة (ANA)',
                'name_en' => 'ANA',
                'category' => LabTestCategory::Infection,
                'sample_type' => SampleType::Blood,
                'suggested_price' => 410,
                'fasting_hours' => null,
                'turnaround_hours' => 72,
                'description_ar' => 'مسح لأمراض المناعة الذاتية.',
                'description_en' => 'Screens for autoimmune disease.',
                'measures_ar' => 'إيجابية ANA والعيار.',
                'measures_en' => 'ANA reactivity and titre.',
                'preparation_ar' => 'لا يحتاج صيامًا.',
                'preparation_en' => 'No fasting.',
                'contains_ar' => 'عينة دم.',
                'contains_en' => 'Blood sample.',
            ],
        ];
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function packages(): array
    {
        return [
            [
                'slug' => 'full-checkup',
                'name_ar' => 'باقة الفحص الشامل',
                'name_en' => 'Full Checkup Package',
                'original_price' => 1470,
                'package_price' => 890,
                'is_featured' => true,
                'tests' => ['cbc', 'lipid', 'liver', 'kidney', 'glucose', 'tsh', 'urine', 'esr'],
                'description_ar' => 'باقة سنوية شائعة في معامل مصر لتقييم الدم والكبد والكلى والسكر والدرقية.',
                'description_en' => 'Popular annual Egyptian lab package for blood, liver, kidney, sugar and thyroid.',
                'includes_ar' => 'CBC، دهون، وظائف كبد وكلى، سكر صائم، TSH، بول، ESR.',
                'includes_en' => 'CBC, lipids, liver and kidney, fasting glucose, TSH, urine, ESR.',
                'conditions_ar' => 'ساري في المعامل المشاركة. غير قابل للاسترداد بعد سحب العينة. للأعمار فوق 16 سنة.',
                'conditions_en' => 'Valid at participating labs. Non-refundable after sample collection. Age 16+.',
                'preparation_ar' => 'صيام 10–12 ساعة. أحضر بطاقة الرقم إن طُلبت. اشرب ماءً.',
                'preparation_en' => 'Fast 10–12 hours. Bring ID if asked. Water is allowed.',
            ],
            [
                'slug' => 'iron-studies',
                'name_ar' => 'باقة الحديد',
                'name_en' => 'Iron Studies Package',
                'original_price' => 630,
                'package_price' => 390,
                'is_featured' => true,
                'tests' => ['cbc', 'ferritin', 'iron', 'tibc'],
                'description_ar' => 'لتقييم الأنيميا ونقص الحديد كما في عروض فيزيتا لمعامل سبيد.',
                'description_en' => 'Anaemia and iron-deficiency panel, similar to common Vezeeta lab offers.',
                'includes_ar' => 'CBC، فيريتين، حديد السيرم، TIBC.',
                'includes_en' => 'CBC, ferritin, serum iron, TIBC.',
                'conditions_ar' => 'لا يشمل علاجًا. النتيجة خلال يوم عمل.',
                'conditions_en' => 'Does not include treatment. Results within one working day.',
                'preparation_ar' => 'صيام 8 ساعات. أوقف مكمل الحديد صباح التحليل.',
                'preparation_en' => 'Fast 8 hours. Skip the morning iron supplement.',
            ],
            [
                'slug' => 'liver-package',
                'name_ar' => 'باقة وظائف الكبد',
                'name_en' => 'Liver Package',
                'original_price' => 458,
                'package_price' => 297,
                'is_featured' => false,
                'tests' => ['liver', 'hbsag', 'hcv'],
                'description_ar' => 'إنزيمات الكبد مع مسح فيروسات ب وسي.',
                'description_en' => 'Liver enzymes plus hepatitis B and C screening.',
                'includes_ar' => 'وظائف كبد شاملة، HBsAg، HCV Ab.',
                'includes_en' => 'Full LFT, HBsAg, HCV Ab.',
                'conditions_ar' => 'نتيجة إيجابية تحتاج تأكيدًا طبيًا وليس تشخيصًا نهائيًا.',
                'conditions_en' => 'A reactive result needs medical confirmation, not a final diagnosis.',
                'preparation_ar' => 'يفضّل صيام 8 ساعات.',
                'preparation_en' => 'Prefer 8 hours fasting.',
            ],
            [
                'slug' => 'hormone-package',
                'name_ar' => 'باقة الهرمونات',
                'name_en' => 'Hormone Package',
                'original_price' => 655,
                'package_price' => 425,
                'is_featured' => true,
                'tests' => ['tsh', 'ft4', 'prolactin', 'testosterone'],
                'description_ar' => 'درقية وخصوبة في طلب واحد.',
                'description_en' => 'Thyroid and fertility hormones in one request.',
                'includes_ar' => 'TSH، T4 حر، برولاكتين، تستوستيرون.',
                'includes_en' => 'TSH, Free T4, prolactin, testosterone.',
                'conditions_ar' => 'قد تختلف التوقيتات حسب الدورة للنساء. استشر طبيبك.',
                'conditions_en' => 'Timing may depend on the menstrual cycle. Ask your doctor.',
                'preparation_ar' => 'سحب صباحي بعد راحة. لا يحتاج صيامًا إلا بطلب الطبيب.',
                'preparation_en' => 'Morning draw after rest. Fasting only if your doctor asked.',
            ],
            [
                'slug' => 'diabetes-lipids',
                'name_ar' => 'باقة السكر والدهون',
                'name_en' => 'Diabetes & Lipids Package',
                'original_price' => 630,
                'package_price' => 410,
                'is_featured' => false,
                'tests' => ['glucose', 'hba1c', 'lipid'],
                'description_ar' => 'متابعة مرضى السكر والكوليسترول.',
                'description_en' => 'Follow-up for diabetes and cholesterol.',
                'includes_ar' => 'سكر صائم، تراكمي، صورة دهون.',
                'includes_en' => 'Fasting glucose, HbA1c, lipid profile.',
                'conditions_ar' => 'لا يغني عن زيارة الطبيب لتعديل العلاج.',
                'conditions_en' => 'Does not replace a doctor visit to adjust treatment.',
                'preparation_ar' => 'صيام 10–12 ساعة.',
                'preparation_en' => 'Fast 10–12 hours.',
            ],
            [
                'slug' => 'heart-package',
                'name_ar' => 'باقة القلب',
                'name_en' => 'Heart Package',
                'original_price' => 1010,
                'package_price' => 690,
                'is_featured' => true,
                'tests' => ['lipid', 'troponin', 'ckmb', 'crp'],
                'description_ar' => 'دهون مع مؤشرات عضلة القلب والالتهاب.',
                'description_en' => 'Lipids plus cardiac enzymes and inflammation.',
                'includes_ar' => 'دهون، تروبونين، CK-MB، CRP.',
                'includes_en' => 'Lipids, troponin, CK-MB, CRP.',
                'conditions_ar' => 'لا يغني عن كشف القلب أو رسم القلب عند الأعراض الحادة.',
                'conditions_en' => 'Does not replace a cardiology visit or ECG for acute symptoms.',
                'preparation_ar' => 'صيام 10 ساعات لصورة الدهون.',
                'preparation_en' => 'Fast 10 hours for the lipid profile.',
            ],
            [
                'slug' => 'fertility-package',
                'name_ar' => 'باقة الخصوبة',
                'name_en' => 'Fertility Package',
                'original_price' => 1020,
                'package_price' => 680,
                'is_featured' => true,
                'tests' => ['fsh', 'lh', 'prolactin', 'tsh', 'hcg'],
                'description_ar' => 'هرمونات الدورة والخصوبة مع TSH وHCG.',
                'description_en' => 'Cycle and fertility hormones with TSH and HCG.',
                'includes_ar' => 'FSH، LH، برولاكتين، TSH، Beta HCG.',
                'includes_en' => 'FSH, LH, prolactin, TSH, Beta HCG.',
                'conditions_ar' => 'توقيت السحب حسب يوم الدورة. استشر طبيبك.',
                'conditions_en' => 'Draw timing depends on the cycle day. Ask your doctor.',
                'preparation_ar' => 'سحب صباحي. صيام فقط إذا طلب الطبيب.',
                'preparation_en' => 'Morning draw. Fast only if your doctor asked.',
            ],
            [
                'slug' => 'vitamin-bone',
                'name_ar' => 'باقة الفيتامينات والعظام',
                'name_en' => 'Vitamins & Bone Package',
                'original_price' => 910,
                'package_price' => 560,
                'is_featured' => false,
                'tests' => ['vitd', 'vitb12', 'calcium', 'cbc'],
                'description_ar' => 'فيتامين د وب12 والكالسيوم مع صورة دم.',
                'description_en' => 'Vitamin D, B12 and calcium with a CBC.',
                'includes_ar' => 'فيتامين د، ب12، كالسيوم، CBC.',
                'includes_en' => 'Vitamin D, B12, calcium, CBC.',
                'conditions_ar' => 'النتيجة خلال يومين عمل.',
                'conditions_en' => 'Results within two working days.',
                'preparation_ar' => 'يفضّل صيام 8 ساعات.',
                'preparation_en' => 'Prefer 8 hours fasting.',
            ],
        ];
    }
}
